server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SIMPLIFICADO: fallback SPA — toda ruta no-archivo sirve index.html
  # para que el router de Angular resuelva /catalogo, /carrito, etc.
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Cache corto para el index, largo para assets con hash
  location = /index.html {
    add_header Cache-Control "no-cache";
  }
}
